language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: nightly

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia --project=Mackey_Glass.jl
      after_success: skip
